M48
; DRILL file {KiCad 9.0.6} date 2025-12-29T23:23:48+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-29T23:23:48+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X206.85Y-103.65
T2
X92.0Y-35.0
X92.0Y-203.5
X215.0Y-203.5
M30
